apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-capstone
  labels:
    app: devops-capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-capstone
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devops-capstone
    spec:
      containers:
      - name: capstone
        imagePullPolicy: Always
        image: ayoalaka/devops-capstone:1.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: devops-capstone
  labels:
    app: devops-capstone
spec:
  type: LoadBalancer
  selector:
    app: devops-capstone
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP